triage:
  label: triage
  dryRun: false

closeAndLock:
  labels:
    - label: "famibot: support"
      message: >
        Thanks for the issue! This issue appears to be a support request. We use this issue tracker exclusively for
        bug reports and feature requests.


        Thank you for using Rindo!
    - label: "famibot: missing template"
      message: >
        Thanks for the issue! It appears that you have not filled out the provided issue template. We use this issue
        template in order to gather more information and further assist you. Please create a new issue and ensure the
        template is fully filled out.


        Thank you for using Rindo!
  close: true
  lock: true
  dryRun: false

comment:
  labels:
    - label: "famibot: needs reproduction"
      message: >
        Thanks for the issue! This issue has been labeled as `needs reproduction`. This label is added to issues that
        need a code reproduction.


        Please provide step-by-step instructions to reproduce your error. Be sure to include your operating system,
        node version, the shell you are using, and any other information that you feel may be useful in reproducing the
        error.


        If you have already provided a instructions and are seeing this message, it is likely that the instructions were
        not enough for our team to reproduce the issue.


        For a guide on how to create a good reproduction, see our
        [Contributing Guide](https://github.com/familyjs/rindo/blob/main/.github/CONTRIBUTING.md).
  dryRun: false

noReply:
  maxIssuesPerRun: 100
  includePullRequests: false
  label: Awaiting Reply
  close: false
  lock: false
  dryRun: false

noReproduction:
  days: 14
  maxIssuesPerRun: 100
  label: "famibot: needs reproduction"
  responseLabel: triage
  exemptProjects: true
  exemptMilestones: true
  message: >
    Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still
    an issue with the latest version of Rindo, please create a new issue and ensure the template is fully filled out.


    Thank you for using Rindo!
  close: true
  lock: true
  dryRun: false

stale:
  days: 30
  maxIssuesPerRun: 100
  exemptLabels:
    - "Bug: Validated"
    - "Feature: Want this? Upvote it!"
    - good first issue
    - help wanted
    - Reply Received
    - Request For Comments
    - "Resolution: Needs Investigation"
    - "Resolution: Refine"
    - triage
  exemptAssigned: true
  exemptProjects: true
  exemptMilestones: true
  label: "famibot: stale issue"
  message: >
    Thanks for the issue! This issue is being closed due to inactivity. If this is still
    an issue with the latest version of Rindo, please create a new issue and ensure the
    template is fully filled out.


    Thank you for using Rindo!
  close: true
  lock: true
  dryRun: false

wrongRepo:
  repos:
    - label: "famibot: cli"
      repo: family-cli
      message: >
        Thanks for the issue! We use this issue tracker exclusively for bug reports and feature requests
        associated with the Rindo CLI. It appears that this issue is associated with the Family CLI.
        I am moving this issue to the Family CLI repository. Please track this issue over there.


        Thank you for using Rindo!
    - label: "famibot: family"
      repo: family
      message: >
        Thanks for the issue! We use this issue tracker exclusively for bug reports and feature requests
        associated with Rindo CLI. It appears that this issue is associated with the Family Framework.
        I am moving this issue to the Family Framework repository. Please track this issue over there.


        Thank you for using Rindo!
  close: true
  lock: true
  dryRun: false
